projects:
  universal-api-prod:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: vf7rrbdfnvgk3ggjez6hytfba4
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://5zypdh43tvathb5373i3eym42i.appsync-api.us-east-1.amazonaws.com/graphql
